### ISSUE TITLE
链接坏掉了

### ISSUE THREAD

**Issue by nkh0472** [zhaobozhen/LibChecker-Docs#81]
https://github.com/zhaobozhen/LibChecker-Docs/blob/master/docs/guide/README.md#%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86

这里的“什么是原生库架构？”指向了一个已经被移动的文件，现在链接已经坏掉了。
新的位置在[这里](https://github.com/zhaobozhen/LibChecker-Docs/blob/master/%E6%96%87%E6%A1%A3/%E6%8C%87%E5%AF%BC/What-is-Native-Library-Architecture.md)。
我顺着app帮助页面的链接才找到了这里。
没整明白为什么要把那个文件的目录移动掉，看起来只是一个意外操作（？）

**Comment by zhaobozhen** [comment]
可能是依赖更新导致行为变更了，有时间我看看

**Comment by nkh0472** [comment]
https://github.com/zhaobozhen/LibChecker-Docs/commit/7640fc83cdc5c100fbebac19383b5a08269a6608这个commit里的注释提到了把这个文件移动了目录

**Comment by zhaobozhen** [comment]
3b3c076f2cb881e76bb4dd8a471d7a46a3adb04f 已修复
